repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-docstring-first
      - id: check-json
      - id: debug-statements
      - id: detect-private-key
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
#   - repo: https://github.com/pycqa/isort
#     rev: 5.12.0
#    hooks:
#      - id: isort
#        name: isort (python)
